services:
  # ========== INFRA ==========
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: hrms
      POSTGRES_PASSWORD: hrms
      POSTGRES_DB: hrms
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrms -d hrms"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./services/postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: devminio
      MINIO_ROOT_PASSWORD: devminiosecret
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio:/data

  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: devkey
    ports: ["7700:7700"]

  # ========== APPS ==========
  api-gateway:
    build:
      context: ../../               # <-- ROOT repo
      dockerfile: apps/api-gateway/Dockerfile
    working_dir: /repo/apps/api-gateway
    env_file:
      - ../../.env.example
    environment:
      PORT: 4000
      NODE_ENV: development
      DATABASE_URL: postgresql://hrms:hrms@postgres:5432/hrms
      JWT_SECRET: super-secret-key
      JWT_EXPIRES_IN: 12h
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: devminio
      MINIO_SECRET_KEY: devminiosecret
      MINIO_BUCKET: cv-private
      MINIO_REGION: us-east-1
      MINIO_USE_SSL: "false"
      MINIO_PRESIGN_EXPIRY: 300
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: devkey
    ports: ["4000:4000"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../../apps/api-gateway:/repo/apps/api-gateway:rw
      - /repo/apps/api-gateway/node_modules
    command: ["npm","run","dev"]

  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
    working_dir: /repo/apps/web
    env_file:
      - ../../.env.example
    environment:
      VITE_API_URL: http://localhost:4000
      PORT: 3000
    ports: ["3000:3000"]
    depends_on:
      api-gateway:
        condition: service_started
    volumes:
      - ../../apps/web:/repo/apps/web:rw
      - /repo/apps/web/node_modules
    command: ["npm","run","dev","--","--host"]

  worker:
    build:
      context: ../../
      dockerfile: apps/worker/Dockerfile
    working_dir: /repo/apps/worker
    env_file:
      - ../../.env.example
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://hrms:hrms@postgres:5432/hrms
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../../apps/worker:/repo/apps/worker:rw
      - /repo/apps/worker/node_modules
    command: ["pnpm","dev"]

  # AI Service
  ai-service:
    build:
      context: ../../
      dockerfile: apps/ai-service/Dockerfile
    working_dir: /repo/apps/ai-service
    env_file:
      - ../../.env.example
    environment:
      PORT: 8000
    ports: ["8000:8000"]
    volumes:
      - ../../apps/ai-service:/repo/apps/ai-service
    command: ["python","-m","uvicorn","src.main:app","--host","0.0.0.0","--port","8000","--reload"]

volumes:
  pgdata:
  minio: